### ISSUE TITLE
Support the head parameter if pbc transport is used. [JIRA: CLIENTS-1039]

### ISSUE THREAD

**Issue by tobixx** [basho/riak-python-client#134]
Rationale: If the key management is out sourced to other systems and huge deletes should be performed there is no need for any data to be transfered. The implementation of this parameter would greatly improve this sort of task by reducing used resources and a noticeable speed up - depending on the data size.

By the way, why is this parameter only available for the pbc api ?

Beside this implementation suggestion, I would generally love to see a much lighter interface for operations which depends only on the key. Specifically I talk about something like:

bucket.delete(key)
bucket.exists(key)

and would just return boolean as no other informations are needed.

**Comment by tobixx** [comment]
Would it not be to hard, if I ask for the reason - why this issue was closed silently without any comment !?

**Comment by lukebakken** [comment]
@tobixx - I don't know the backstory for this issue, but I've scheduled #502 to be in `2.7.0`. Thanks!

**Comment by tobixx** [comment]
Thanks!

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
