### ISSUE TITLE
RiakMapReduce not working with .search as expected. [JIRA: CLIENTS-130]

### ISSUE THREAD

**Issue by gglanzani** [basho/riak-python-client#393]
As above, or I'm simply doing it wrong. In that case slap me in the face.

The code that I have is (the reduce code is quite stupid, but bear with me: I wanted to get something working):

```python
mr = RiakMapReduce(riak)
mr.search(index="grid_stats", query="industry_id:22 AND customer_segmentation_id:6")
mr.map("""function(value) {
var data = Riak.mapValuesJson(value)[0];
if (data.year > 2006) {
var obj = {};
obj[data.grid_id] = data.year
return [obj];
}
return []
}""", options={"language": "javascript", "keep": False})
mr.reduce("""function(values) {
return [values.reduce(function(acc, item) {
        for (i in item) {
            acc[i] += item[i];
        }  
        return acc;})];
}
""", options={"language": "javascript", "keep": True})
for result in mr.run():
    print "%s" % result
```

It gives me the output 

```
{u'not_found': u'[object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object][object Object]'}
```

If I replace the `mr.search` line with the following lines

```python
keys = [d['_yz_rk'] for d in bucket.search(query="industry_id:22 AND customer_segmentation_id:6", index="grid_stats")['docs']]
mr.add("STATS", keys)
```

then the output becomes:

```
{u'9533906': 16084}
```

which is what I expected in the first place. Am I doing something wrong or is something else going on?

EDIT: forgot to mention I'm using the latest (2.2.0) version from pip

**Comment by pigmej** [comment]
I think this one is related to: https://github.com/basho/riak/issues/618

**Comment by gglanzani** [comment]
@pigmej Yes, I think that as well. Too bad basho still has to reply to the bug report.

**Comment by gglanzani** [comment]
@javajolt Hi Brett, could this be related to https://github.com/basho/yokozuna/issues/360?

It seems @coderoshi was on to something with the bucket type fix (Note: the buckets against which I query do not have any type associated with them).

**Comment by javajolt** [comment]
@gglanzani It's possible Search is being called incorrectly from Python.  Thanks for the link to the other issue.  I hope to find some time in the near term to look at your M/R issues.

**Comment by pigmej** [comment]
Just in case @javajolt in my issue basho/riak#618 there is no python involved at all (plain curl examples). So if both are related then it's other case.

**Comment by javajolt** [comment]
@gglanzani Are you happy tracking this issue in basho/riak#618 since it appears to be a Riak, not Python client, problem?

**Comment by pigmej** [comment]
@javajolt @gglanzani  already responded in basho/riak#618 ...

**Comment by javajolt** [comment]
Closing since this appears to be core, not Python client, issue

**Comment by Basho-JIRA** [comment]
This appears to be a core issue, not a Python client one 

***[posted via JIRA by Brett Hazen]***
