### ISSUE TITLE
Less keys processed/returned when using MR [JIRA: CLIENTS-134]

### ISSUE THREAD

**Issue by gglanzani** [basho/riak-python-client#395]
Third bug report in two days: I'll promise I'll stop for a while, as tomorrow I'll undergo surgery :)

I've put the code in [this gist](https://gist.github.com/gglanzani/440795adaaa22620500e) to ease the flow.

The problem is twofold:

In python_code1.py, I try to process 40 keys, and I get the traceback in the python_tb1.py file.

If I lower the number of keys (python_code2.py), I get the results, but I have less keys (15) instead of the 27 unique keys that I fed to the MR code.

Anybody has a clue?

Edit: as far as the second problem goes, I've found the issue.

**Comment by seancribbs** [comment]
Looks like your final reduce function has no clause that matches its given arguments (that's the meaning of `function_clause`).  You can also directly feed [searches directly into mapreduce](http://riak-python-client.readthedocs.org/en/2.2.0/query.html#riak.mapreduce.RiakMapReduce.search).

**Comment by gglanzani** [comment]
@seancribbs I'll look into the clause stuff.

BTW, feeding searches doesn't seem to work either, see https://github.com/basho/riak-python-client/issues/393

**Comment by seancribbs** [comment]
@gglanzani Thanks, we'll look into it.

**Comment by pigmej** [comment]
@gglanzani @seancribbs 
In fact the search feeding problem is more general: https://github.com/basho/riak/issues/618 

It happens outside python client.

**Comment by gglanzani** [comment]
Ok, I think this can be closed. I think it's an issue of mochijson2 version 4.x because when I try the same query on my machine (mochijson2 version 5.x), I don't get the function_clause problem.

**Comment by Basho-JIRA** [comment]
The associated GitHub issue was closed. 

***[posted via JIRA by Derek Somogyi]***
