### ISSUE TITLE
Timeout: Socket returned short packet length 0 [JIRA: CLIENTS-215]

### ISSUE THREAD

**Issue by Tinche** [basho/riak-python-client#399]
Hello,

we're using Riak over protocol buffers, and with Amazon's Elastic Load Balancer in the middle. We're seeing these exceptions pop out:

```
Error while storing avatar to Riak: 'Socket returned short packet length 0 - expected 4'
```

(Here's another person with a similar issue: http://codersdiscuss.com/4870/timeout-issues-with-the-riak-python-customer-with-process-buffers/.)

As far as we can see, it's the idle timeout setting of the ELB that's the problem - a worker can be idle for more than the idle timeout, and ELB will close some (or both - to the worker and to Riak) of the connections. Then, the next Riak action will result in the above exception.

We will probably deal with this on the application layer. However, it'd be very convenient if this could be dealt with on the pool layer transparently.

According to Python docs (https://docs.python.org/2/howto/sockets.html):
```
When a recv returns 0 bytes, it means the other side has closed (or is in the process of closing) the connection. You will not receive any more data on this connection. Ever.
```

The RiakPbcPool class already has a set of exceptions on which to retry calls. How about adding this particular case to the set of auto-retry scenarios?

**Comment by javajolt** [comment]
@Tinche Is the ELB closing the connections automatically?  You are wanting the client to retry on a "short packet length error?"

**Comment by Tinche** [comment]
@javajolt 

Yes, I think the ELB is closing the connections automatically.

Yes, I'd like the retry mechanism to handle these errors (short packet length error: 0, indicating a closed or closing connection) by reopening the connection, like it does for ECONNRESET or ETIMEDOUT. Does this seem reasonable?

**Comment by ellulpatrick** [comment]
We had the same problem (although not due to AWS ELB). The underlying network might close the connection due to inactivity and the code only finds out on the next request. We decided to use TCP keepalives to stop the problem from happening. See the change we made to allow this at https://github.com/iPowow/riak-python-client/commit/f4e111e31567de4ea3d7351c45da34b1b97669f4 . Having said that, it's probably still a good idea to consider this as a retryable exception.

**Comment by lukebakken** [comment]
@ellulpatrick - thank you for that information. We will probably include that in the next Python client release.

**Comment by mcobzarenco** [comment]
+1

**Comment by Tinche** [comment]
Thanks!
