### ISSUE TITLE
support for Python 3 [JIRA: CLIENTS-539]

### ISSUE THREAD

**Issue by adiri** [basho/riak-python-client#409]
3.4 to be accurate :)

**Comment by javajolt** [comment]
@adiri Can you be more specific about what problem(s) you are having with Python 3.4.x?

**Comment by adiri** [comment]
@javajolt i'm reviewing it right now :) I'll update.

**Comment by javajolt** [comment]
Any more details? We do already support Python 3.4.x. Let me know if you are having problems.

**Comment by lukebakken** [comment]
Closing - no response.
