### ISSUE TITLE
How could I upload a file to my remote riak server? [JIRA: CLIENTS-618]

### ISSUE THREAD

**Issue by adrrodgar** [basho/riak-python-client#413]
Hi everybody,

 I am developing a software on Windows 7 and I need to upload files to a remote server with Riak.
In the documentation not it is clear to me how to do it.
Could anyone help me?

Thanks, 
Adrian

**Comment by javajolt** [comment]
@adrrodgar Have you tried the mailing list, http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com?  Also, have you considered our .NET client? https://github.com/basho/riak-dotnet-client

Using Python on Windows *should* work as anywhere else, https://www.python.org/downloads/windows/ or http://www.activestate.com/activepython.

We have not tested the Python client under Windows, but in theory it should work fine.

**Comment by adrrodgar** [comment]
Hi, 
Excuse me for taking so long to answer you.
I have installed Python 3.4.3 in Windows 7 and the riak 2.2.0 library. the problem is that it won't let me upload anything to my bucket if it is not through HTTPS and from what I read in riak documentation uses HTTP and Pbc, but I can not find how to do it over HTTPS.

**Comment by javajolt** [comment]
Here is a whole section of documentation about the Python client and security: http://docs.basho.com/riak/latest/dev/advanced/client-security/python/

**Comment by adrrodgar** [comment]
OK, thank you very much, I will look at me how to upload it with the certificate, user, and password.
