### ISSUE TITLE
Deleted VClocks in the documentation [JIRA: CLIENTS-703]

### ISSUE THREAD

**Issue by lucasbru** [basho/riak-python-client#424]
http://docs.basho.com/riak/latest/ops/advanced/deletion/ notes that it is not possible to query deleted vclocks:

```
# It is not currently possible to fetch the causal context for a deleted
# key in the Python client.
```

However, #332 notes that this is turned on by default. Please update the documentation.

**Comment by lukebakken** [comment]
Thank you for reporting this. Since it affects our documentation, I have opened this issue:

basho/basho_docs#1929
