### ISSUE TITLE
Clarification needed on bucket handling [JIRA: CLIENTS-744]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-python-client#428]
From [this question on stackoverflow:](http://stackoverflow.com/questions/35071944/is-riak-bucket-object-cachable?noredirect=1#comment57906384_35071944) by @schultz9999

> What we see is that every now and then, client.bucket(bucket_name) returns None while the bucket is clearly there on every one (I checked manually). So the supposition is that asking Riak for a bucket often enough does something that result None returned. I played with caching a bucket for 10 seconds and it appears mitigates the problem. I would love to understand better though why this happens.

**Comment by lukebakken** [comment]
@schultz9999 - could you please provide a more complete code example? What I don't understand is that, since a bucket doesn't really exist as an entity in Riak, how you're getting `None` back. You can see [the code here.](https://github.com/basho/riak-python-client/blob/master/riak/client/__init__.py#L220-L253). There could always be a bug in how the `WeakValueDictionary` is used.

**Comment by schultz9999** [comment]
That's correct. I kept the object around. However while posting this code here, I asked myself if getting a bucket object is thread-safe even though Python threading model is rather rudimentary. This is because I use tornado:

`
    @gen.coroutine
    def set(self, bucket_name, key, value):
        try:
            bucket = self.get_bucket(bucket_name)
            pair = bucket.new(key, data=value)
            pair.store()
        except socket.error:
            raise RiakStoreException('Riak is not reachable')
        except:
            self._error_logger.error({
                'msg': 'Unexpected error while setting a value in Riak.',
                'bucket': bucket_name,
                'key': key,
                'value': value
            })
            raise

    @gen.coroutine
    def get(self, bucket_name, key):
        try:
            bucket = self.get_bucket(bucket_name)
            value = bucket.get(key)
            if value:
                value = value.data
        except socket.error:
            raise RiakStoreException('Riak is not reachable')
        except:
            self._error_logger.error({
                'msg': 'Unexpected error while getting a value from Riak.',
                'bucket': bucket_name,
                'key': key,
            })
            raise

        raise gen.Return(value)

from repoze.lru import lru_cache
_BUCKET_CACHE_TIMEOUT = 10.0

    @lru_cache(maxsize=5, timeout=_BUCKET_CACHE_TIMEOUT)
    def get_bucket(self, bucket_name):
        result = self._client.bucket(bucket_name)
        if result is None:
            # this is where it happens if I don't do caching.
        return result
`

**Comment by schultz9999** [comment]
Worth noting that my overall call latency went down quite a bit since I start caching buckets. I really wonder if I could cache them for longer than 10 seconds. Although don't think it matters much.

**Comment by lukebakken** [comment]
This is definitely related to #405
