### ISSUE TITLE
version 2.4 not available on PyPI through pip [JIRA: CLIENTS-748]

### ISSUE THREAD

**Issue by jforcada** [basho/riak-python-client#429]
Hi, I cannot download the 2.4 version of riak-python-client with pip. If I do:

`$ pip install riak`

Version 2.3 is downloaded. If I do:

`$ pip install riak==2.4.0`
I get:
`Could not find a version that satisfies the requirement riak==2.4.0 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.0rc1, 2.2.0, 2.3.0, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.0rc1, 2.2.0, 2.3.0)`

But PyPI website says it's available: https://pypi.python.org/pypi/riak

**Comment by lukebakken** [comment]
What is the output of `python --version` and `pip --version`?

**Comment by lukebakken** [comment]
@javajolt - any ideas on this? I see the same issue:

```
Collecting riak==2.4.0
  Could not find a version that satisfies the requirement riak==2.4.0 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc1, 2.1.0, 2.2.0, 2.3.0)
No matching distribution found for riak==2.4.0
```

Runing `pip install` with the `-vvv` flag shows this:

```
Skipping link https://pypi.python.org/packages/3.5/r/riak/riak-2.4.0-py3.5.egg#md5=7e5d43d6732fd1dd865faf9925909f25 (from https://pypi.python.org/simple/riak/); unsupported archive format: .egg
```

Investigating now.

**Comment by lukebakken** [comment]
Looks like `sdist` wasn't built, sigh.

https://docs.python.org/2/distutils/sourcedist.html

**Comment by lukebakken** [comment]
@jforcada - thanks for reporting this, the issue is resolved now.

**Comment by javajolt** [comment]
@lukebakken Glad you got it resolved
