### ISSUE TITLE
Installation fails with setuptools 20.2.1 [JIRA: CLIENTS-778]

### ISSUE THREAD

**Issue by kesslerm** [basho/riak-python-client#439]
A customer reported that the installation fails with setuptools 20.2.1

> riak python lib fails to install with setuptools 20.2.1:
>
>2:11:03,002 INFO - error in riak setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'<2.6.0'"

>as a WA we can add the "setuptools<20.2.1" line to requirements.txt

Confirmed this on OSX, too:

>pip install --upgrade riak riak-pb
>Collecting riak
>  Downloading riak-2.4.2.tar.gz (175kB)
>    100% |████████████████████████████████| 176kB 786kB/s
>    Complete output from command python setup.py egg_info:
>    error in riak setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'<2.7.0'"

>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in >/private/var/folders/_v/n2_n__td58xb66t_hzqs8zb80000gn/T/pip-build-OxOxFV/riak

**Comment by kesslerm** [comment]
This appears to be a widespread problem with other python packages, too.

See related bug reports on the setuptools bitbucket site:

https://bitbucket.org/pypa/setuptools/issues/501/error-installing-zopeapppublication-with
https://bitbucket.org/pypa/setuptools/issues/502/packaging-164-does-not-allow-whitepace
https://bitbucket.org/pypa/setuptools/issues/503/pkg_resources_vendorpackagingrequirementsi

This report (https://github.com/pypa/packaging/issues/65) suggests that setuptools-20.2.1 doesn't follow the specs set out in PEP 440 (https://www.python.org/dev/peps/pep-0440/#version-specifiers)

**Comment by kesslerm** [comment]
The regression in setuptools appears to have been introduced in https://bitbucket.org/pypa/setuptools/commits/67a39c3c7c15f4a71391e1e9f3a661e46f3566dc with the intention to fix https://bitbucket.org/pypa/setuptools/issues/499/version-202-doesnt-like-non-numeric.

**Comment by kesslerm** [comment]
The setuptools maintainer has pulled 20.2.1 from Pypi (https://bitbucket.org/pypa/setuptools/issues/502/packaging-164-does-not-allow-whitepace#comment-25763067).

Closing this issue as resolved

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
