### ISSUE TITLE
Support erlang term-to-binary encoding of messages [JIRA: CLIENTS-802]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-python-client#445]
This will be for timeseries messages at this point.

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak-python-client/issues/445 

***[posted via JIRA by Luke Bakken]***

**Comment by Basho-JIRA** [comment]
PR:
https://github.com/basho/riak-python-client/pull/448  

***[posted via JIRA by Derek Somogyi]***

**Comment by Basho-JIRA** [comment]
reviewed PR, looks good. 

***[posted via JIRA by Christopher Mancini]***
