### ISSUE TITLE
Client hangs after receiving unexpected message code [JIRA: CLIENTS-1012]

### ISSUE THREAD

**Issue by jagguli** [basho/riak-python-client#497]
We have hit a strange issue with the python Riak client, 
which causes the client to lock up our application process. 

I have not yet been able to replicate the exact error,
but I have been able to replicate similar error by executing a
delete on a bunch of keys from the ipython shell,
killing the function execution and trying the operation again. 

May be related to https://github.com/basho/riak-python-client/issues/425

I'm using the python client version:2.5.5 client and server riak_2.1.4-1_amd64.deb

Here's the extract of the logs:

```
RiakError: 'unexpected message code: 1, expected 83'
% (resp_code, expect))
File "/usr/local/lib/python2.7/dist-packages/riak/codecs/__init__.py", line 21, in maybe_incorrect_code
codec.maybe_incorrect_code(resp_code, expect)
File "/usr/local/lib/python2.7/dist-packages/riak/transports/tcp/transport.py", line 549, in _request
resp_code, resp = self._request(msg, codec)
File "/usr/local/lib/python2.7/dist-packages/riak/transports/tcp/transport.py", line 515, in update_datatype
include_context=include_context)
File "/usr/local/lib/python2.7/dist-packages/riak/client/operations.py", line 1143, in update_datatype
self.bucket._client.update_datatype(self, **params)
File "/usr/local/lib/python2.7/dist-packages/riak/datatypes/datatype.py", line 165, in update
self._riak_obj.store()

```

**Comment by lukebakken** [comment]
Thanks for the report.

* Did any other errors happen around the same time?
* Message code `1` is a [ping request code](https://github.com/basho/riak_pb/blob/develop/src/riak_pb_messages.csv#L2) which, to be honest, I have no idea how it got sent *to* your application. In your environment, are you using a proxy of any kind?
* Are any clients executing ping requests against Riak? (for health check, for instance)
* Could you please archive the logs from all of your Riak nodes from that time period and attach the archive file to this issue?

**Comment by jagguli** [comment]
Yes I  am using haproxy, using this connfig

```
global
           log 127.0.0.1     local0
           log 127.0.0.1     local1 notice
           maxconn           256000
           chroot            /var/lib/haproxy
           user              haproxy
           group             haproxy
           spread-checks     5
           daemon
           quiet

       defaults
           log               global
           option            dontlognull
           option            redispatch
           option            allbackups
           maxconn           256000
           timeout connect   5000
 backend riak_protocol_buffer_backend
           balance            leastconn
           mode               tcp
           option             tcpka
           option             srvtcpka
           server hawk0 hawk0.streethawk.com:8087 weight 1 maxconn 1024  check
           server hawk1 hawk1.streethawk.com:8087 weight 1 maxconn 1024  check
           server hawk2 hawk2.streethawk.com:8087 weight 1 maxconn 1024  check
           server hawk3 hawk3.streethawk.com:8087 weight 1 maxconn 1024  check


       frontend riak_protocol_buffer
           bind               0.0.0.0:18087
           mode               tcp
           option             tcplog
           option             contstats
           mode               tcp
           option             tcpka
           option             srvtcpka
           default_backend    riak_protocol_buffer_backend

**Comment by jagguli** [comment]
output of riak-debug https://drive.google.com/drive/folders/0B7tLD0INuYReODJ6V29xWFdHd1E?usp=sharing

**Comment by jagguli** [comment]
Is this possibly related  to threading, This is happening in my celery tasks which are run in concurrent queues.

October 17th 2016, 14:59:25.911	RiakError: 'unexpected message code: 81, expected 20'	hawk3
October 17th 2016, 14:59:25.903	RiakError: 'unexpected message code: 83, expected 81'	hawk3
October 17th 2016, 14:59:25.896	RiakError: 'unexpected message code: 81, expected 20'	hawk3

**Comment by lukebakken** [comment]
It could be related to threading. Are you sharing the `RiakClient` instance between your tasks?

**Comment by lukebakken** [comment]
How are the concurrent queues started? With `fork()` ?

**Comment by seanjensengrey** [comment]
@jagguli I got similar error codes when I had improper sharing of a `RiakClient` instance across processes.

**Comment by jagguli** [comment]
So I have concurrent celery workers and they have threads too.

**Comment by jagguli** [comment]
Closing this issue, in summary, 

1. create new riak client for each thread/ (in my case each celery task execution)
2. set LimitNOFILE/DefaultLimitNOFILE in systemd unit for systemd based services

**Comment by lukebakken** [comment]
@jagguli 

> create new riak client for each thread

FWIW, you *can* share a `RiakClient` instance across threads, but not *processes*. Does celery use multiple processes (i.e. via `fork()`) to execute tasks?

**Comment by jagguli** [comment]
Corrected processes, thx
