### ISSUE TITLE
Re-try initial operation if socket is closed [JIRA: CLIENTS-1049]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-python-client#503]
When a command is executed against Riak if the chosen socket is closed, an error will occur. This could happen on stale connections if a load balancer (like ELB) times out. Some operations aren't automatically re-tried, but in the case of an immediate socket failure, all Riak operations should be re-tried at least once with a new connection.

basho/riak-clients#6

**Comment by lukebakken** [comment]
I'm using [this `haproxy` config](https://gist.github.com/lukebakken/81c0609c274b083272f182443a6267f5) to simulate ELB closing connections.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
